[package]
name = "valu3-derive"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "crates-io.md"
authors = ["Philippe Assis <codephilippe@gmail.com>"]
repository = "https://github.com/purp-lang/valu3"
keywords = ["valu3", "serialization", "deserialization", "serde", "any"]
description = "A generic serialization/deserialization/type framework"
categories = ["encoding", "no-std"]

[dependencies]
syn = { version = "2.0.13", features = ["full"] }
quote = "1.0.9"
proc-macro2 = "1.0.56"

[dev-dependencies]
valu3 = { version="0.1", path = "../valu3" }

[lib]
proc-macro = true

[[example]]
name = "derive"
required-features = []