[package]
name = "valu3"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "readme.md"
auhtors = ["Philippe Assis <codephilippe@gmail.com>"]
repository = "https://github.com/14bislab/valu3"
keywords = ["value", "generic", "type", "serde"]
documentation = "https://docs.rs/valu3"
description = "A generic serialization/deserialization/type framework"
categories = ["encoding", "no-std"]

[dependencies]
pest="2.5.7"
pest_derive="2.5.7"
regex = "1.7.3"
chrono = "0.4.24"
serde = { version = "1.0.159", features = ["derive"], optional = true }

[features]
default = ["parser"]
parser = ["json"]
json = []
serde = ["dep:serde"]

[lib]
doctest = false