[package]
name = "valu3"
version = "0.3.12"
edition = "2021"
license = "MIT"
readme = "crates-io.md"
authors = ["Philippe Assis <codephilippe@gmail.com>"]
repository = "https://github.com/purp-lang/valu3"
keywords = ["value", "generic", "type", "serde", "any"]
description = "A generic serialization/deserialization/type framework"
categories = ["encoding", "no-std"]
documentation = "https://docs.rs/valu3"

[dependencies]
pest="2.7.6"
pest_derive="2.5.7"
regex = "1.10.3"
chrono = "0.4.33"
serde = { version = "1.0.196", features = ["derive"], optional = true }
valu3-derive = { path = "../valu3_derive", optional = true, version="0.3.12" }

[features]
default = ["parser", "derive"]
parser = ["json"]
json = []
serde = ["dep:serde"]
cstring = []
derive = ["dep:valu3-derive"]

[lib]
doctest = false
