[package]
name = "valu3"
version = "0.1.8"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "crates-io.md"
authors = ["Philippe Assis <codephilippe@gmail.com>"]
repository = "https://github.com/purp-lang/valu3"
keywords = ["value", "generic", "type", "serde", "any"]
description = "A generic serialization/deserialization/type framework"
categories = ["encoding", "no-std"]
documentation = "https://docs.rs/valu3"


[dependencies]
pest="2.5.7"
pest_derive="2.5.7"
regex = "1.7.3"
chrono = "0.4.24"
serde = { version = "1.0.159", features = ["derive"], optional = true }

[features]
default = ["parser"]
parser = ["json"]
json = []
serde = ["dep:serde"]
cstring = []

[lib]
doctest = false