name: Cargo Publish Valu3

on:
  push:
    tags:
      - '*'
    paths:
      - "valu3-parquet/**"

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cogup/cargo@master
        with:
          command: publish
          args: --verbose -p valu3-parket
