name: Cargo Publish Valu3 Derive

on:
  push:
    tags:
      - '*'
    paths:
      - 'valu3_derive/**'

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --verbose -p valu3-derive
